name: CI

on:
  push:
    branches:
      - master

env:
  PROPERTIES_PATH: "./android/key.properties"

jobs:
  flutter_format_analyze_test:
    name: Run flutter test and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: dart format -l 80 --set-exit-if-changed .
      - run: flutter analyze .
      - run: flutter test

      - run: |
          echo keyPassword=\${{ secrets.KEY_STORE }} > ${{env.PROPERTIES_PATH}}
          echo storePassword=\${{ secrets.KEY_PASSWORD }} >> ${{env.PROPERTIES_PATH}}
          echo keyAlias=\${{ secrets.KEY_ALIAS }} >> ${{env.PROPERTIES_PATH}}
      # Decoding base64 key into a file
      - run: echo "${{ secrets.KEYSTORE2 }}" | base64 --decode > android/app/key.jks


      - run: flutter build apk --release -t lib/main_prod.dart --flavor=prod --dart-define URL=${{ secrets.URL }} --dart-define token=${{ secrets.token }}


      - name: Upload artefato
        uses: actions/upload-artifact@v2
        with:
          name: app-prod-release
          path: build/app/outputs/flutter-apk/
    
       - name: upload artifact to Firebase App Distribution

      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: ${{secrets.APPID}}
        serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
        groups: test
        file: build/app/outputs/flutter-apk/app-prod-release.apk